name: action on push
on: [push, workflow_dispatch]
jobs:
  use-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Composite action
        uses: nicovince/hello-world-composite-action@main

  use-composite-with-custom-container:
    name: Custom Container call reusable composite
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/siemaapplications/zephyr-arm-build:v0.0.3
      volumes:
        - /home/runner/work/_actions/nicovince/hello-world-composite-action/main:/home/runner/work/_actions/nicovince/hello-world-composite-action/main
    steps:
      - name: Composite action
        uses: nicovince/hello-world-composite-action@main

