name: Zephyr Release
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'sandbox-app-v*'

permissions:
  contents: write # to create release

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  app_release:
    name: Zephyr Application Release
    uses: SiemaApplications/vossloh-gh-actions/.github/workflows/release-zephyr-signed-app.yml@twister-sign-binaries
    with:
      app-dir: zephyr/samples
      key-file: key.pem
      twister-outdir: twister-app
      tests-names: |
        samples/subsys/usb/dfu/sample.usb.dfu
        samples/hello_world/sample.basic.helloworld
      boards: nucleo_h743zi
      integration: false
      project: sandbox
      application: app
    secrets:
      signing-key: ${{ secrets.MCUBOOT_SANDBOX_KEY }}
